fastnbt/src/anvil/draw.rs
fastnbt/src/anvil/mod.rs

This extends `fastnbt::anvil::Region` to do chunk loading and decompression (but not NBT decoding). 
Most usefull probably is `.load_chunk_nbt_at_location(x, z)` which handles location lookup and decompression.
Changing draw.rs to use  `.load_chunk_nbt_at_location(x, z)` for some reason makes `anvil render` run somewhat fasters for reasons I do not have looked into.
Also notable is `.for_each_chunk()` which moves iteration into fastnbt::anvil::Region.

Anvil based chunk loading (instead of draw.rs)

---

tools/src/bin/anvil.rs

Some Minecraft world edit tools - e.g. the very common "mcaselector" - tend to leave 0-sized files. This results in Maps with too much black borders, like http://f.foxel.org/map.png. So this patch skips 0 length files.

Ignore Anvil/Region Files with file size 0

---

tools/src/bin/anvil.rs

Something like `minecraft/saves/zombie survival ep.1/` results in a failure eithin `coords_from_region()`. Parsing from the end of the filename should fix that.

Allow world names with a `.` in the file path

---

fastnbt/src/stream.rs
fastnbt/src/test/stream.rs

When parsing a size prefixed string, the stream parser attempts to parse the string as UTF-8 via the standard library, which errors on Minecraft's CESU-8 (Java variant) encoded string.  This also causes attempts to skip over a compound containing a string to fail.
0be03dc1877c0e19810f96d9f7e2ac728ad6c64c has fixed this in the Serde parser but not the stream parser.
Unrelated: I think it's a good idea to change the error from a string to a custom error type (by using `thiserror`) so that users can check what error has occurred without relying on the content of the string. What do you think?

Fix: stream parser errors on Minecraft Unicode

---

tools/src/bin/region-dump.rs

Currently both `json` and `json-pretty` outputs are the same compact format - probably because they're both using the same [`to_writer`](https://docs.serde.rs/serde_json/fn.to_writer.html) call from `serde_json`.  Changing the `json-pretty` output to use [`to_writer_pretty`](https://docs.serde.rs/serde_json/fn.to_writer_pretty.html) gives the desired effect.

Fix the `json-pretty` output to be pretty

---

fastnbt/src/lib.rs
fastnbt/src/macros.rs
fastnbt/src/test/macros.rs
fastnbt/src/test/mod.rs
fastnbt/src/value.rs

This adds a `nbt!` macro similar to the `json!` macro from [serde_json](https://github.com/serde-rs/json). The code is actually mostly copied from there, but modified for NBT.
An example usage might look like this:
```rs
nbt!({
"Items": [
{
"tag": {},
"id": "minecraft:axolotl_bucket",
"Count": 1_u8,
"Slot": 0_u8,
},
{
"id": "minecraft:stick",
"Count": 42_u8,
"Slot": 1_u8,
},
{
"id": "minecraft:stone",
"Count": 64_u8,
"Slot": 11_u8,
},
]
})
```
I have taken the simple approach of turning expressions into `fastnbt::Value`s and implemented the `From<T>` trait for a few types (all number types, `String`, `&str`, `ByteArray`, `IntArray`, `LongArray`, and all their referenced versions). If you would like me to do it the `serde_json` way and implement a Serializer with `fastnbt::Value` as the …

Add `nbt!` macro

---

fastnbt/src/de.rs
fastnbt/src/ser/serializer.rs
fastnbt/src/test/de.rs
fastnbt/src/test/ser.rs
fastnbt/src/value.rs

This PR adds support for (de)serializing `i128` and `u128` from/to NBT IntArrays of length 4. Minecraft always saves UUIDs as IntArrays with 4 entries which perfectly matches 128 bits.

Add 128-bit integer support

---

fastnbt/src/arrays.rs
fastnbt/src/error.rs
fastnbt/src/lib.rs
fastnbt/src/macros.rs
fastnbt/src/test/value/de.rs
fastnbt/src/test/value/mod.rs
fastnbt/src/test/value/ser.rs
fastnbt/src/value/array_serializer.rs
fastnbt/src/value/de.rs
fastnbt/src/value/mod.rs
fastnbt/src/value/ser.rs

Another feature ported from `serde_json`:

Add (de)serializer to/from Value

---

fastnbt/src/arrays.rs

This pull request allows arrays to be modified in-place without making copies, which makes editing and writing back large NBT tags more efficient.

Impl DerefMut for arrays

---

fastanvil/src/region.rs

This is blocking me from updating to the latest version.

Remove unneeded Write bound from RegionIter

---

fastanvil/src/java/mod.rs
fastanvil/src/java/pre13.rs
fastanvil/src/java/pre13/pre13_block_names.rs

This was easier than expected, but there are some missing things. However it is enough for my use case of "finding blocks by name", so it may be useful. I tested the `Chunk::block` API in every version from 1.2 to 1.13 and it seems to work.

Rough support for pre 1.13 worlds

---

Cargo.lock
fastanvil/Cargo.toml

I noticed `hematite-nbt` in the list of compiled crates and was surprised, since `fastnbt` does roughly the same. Indeed, it seems to be unused - [cargo-udeps](https://crates.io/crates/cargo-udeps) agrees, and `rg "hematite"` doesn't find any mentions of it in the source code.
`cargo test` on the entire workspace passes both before and after the removal.
That dependency was added by https://github.com/owengage/fastnbt/commit/5151cddf3578cb79b2cbb96cf62cc4a3d0f7b884, a commit with no code changes that adds a benchmark comparing `fastnbt` and `hematite-nbt` to the readme, so possibly it was added by accident.

Remove unused fastanvil dependency on hematite-nbt

---

fastnbt/src/arrays.rs

Otherwise there is no efficient way to do this without allocating a new vector.

Add into_inner() to ByteArray, IntArray, LongArray

---

fastanvil/src/region.rs
fastanvil/src/test/region.rs

Unfortunately I did not find a way to truncate the buffer without having access to an underlying `File` or so.
Maybe add an `impl<File> Region` so we can use [`set_len`](https://doc.rust-lang.org/std/fs/struct.File.html#method.set_len)?
Note: I derived `Clone` on Region as the test `deleted_chunk_at_end_of_buffer_truncates_buffer` uses `into_inner` which consumes self. Please tell me if there's any better way to do so
PS: I'm pretty new to Rust so please don't hesitate to correct mistakes and improve the code :)

Add remove_chunk() to Region and tests

---

fastnbt/src/stream.rs

Following `std::io::Cursor`. Allows retrieving back the original reader from the parser.

Add Parser::{get_ref, get_mut, into_inner}

---

Cargo.lock
fastanvil/src/region.rs
fastanvil/src/test/region.rs

Also updates `Region::location` to integrate the non-existing check, making it less likely to forget to handle this case.
fixes #90

Skip deleting non-existing chunks from a region

---

fastanvil/src/java/pre13/mod.rs

I was doing a quick audit of my dependencies and noticed this unnecessary `unsafe` usage. To make an array of `!Copy` but const-constructible types you just need to create a `const` value to use as the prototype in the array literal.

Replace unsafe usage in fastanvil by const-init

---

README.md
fastanvil/src/biome.rs
fastnbt/src/lib.rs
fastnbt/src/stream.rs
fastnbt/src/test/minecraft_chunk.rs

This PR updates all Gamepedia, owned now by Fandom, urls accordingly.

Update Gamepedia wiki links to new domain

---

fastnbt/src/ser/serializer.rs

Expanded `no_root!` macro to cover more functions, including cases with generics and multiple arguments.

Expand `no_root!` macro

---

fastnbt/src/lib.rs
fastnbt/src/test/mod.rs

Refactored the `From<Tag>` implementation to utilize direct casting instead of a match expression.

Simplify `From<Tag> for u8` Implementation with Direct Cast

---

fastnbt/src/de.rs
fastnbt/src/lib.rs

This adds support for post 1.20.2 networked NBT which doesn't encode compound tag names.
Pretty basic changes just adds a new deserialize option and a single if statement.
closes #103

Add support for "network NBT"

---

fastnbt/src/test/de.rs

Some tests for networked NBT as discussed in #109.
I decided not to add a test for deserializing a named root tag with a network deserializer because it's kinda always going to do some funny behavior. e.g. if the name length is less than 255 it will just read it as an empty compound or if the name is greater than 255 it'll try read the first byte as a type and go down hill from there.

Add tests for network NBT.

---

fastanvil/src/rendered_palette.rs

This pull request updates the `rendered_palette.rs` file to add support for rendering the newly renamed "short_grass" block in the game.
**Changes:**
- Added `short_grass` to the pick_grass match case in `rendered_palette.rs` to rendering grasses.
**Motivation:**
The recent update in Minecraft version 1.20.3 Pre-Release 1 renamed "Grass" to "Short Grass". This necessitates our renderer to recognize and properly render the `short_grass` block. For more details on this update, please refer to the Minecraft Wiki: [Short Grass Update Details](https://minecraft.wiki/w/Short_Grass).

Support rendering of short_grass in rendered_palette.rs

---

tools/src/lib.rs

This pull request adds support for specific blocks that are currently not handled properly due to unique blockstates. The changes include the addition of exception handlers when `make_palette`.
I'm not sure if my approach is the correct way to support new blocks. If my implementation is incorrect, please give me advice of the proper way to extend support for blocks with unique blockstates.
Below are the detailed implementations proposed for two blocks, explaining the error causes and the solutions applied.
- **pink_petals**
- **Error Description:** `Blockstate::Multipart` -> try_mappings
- **Implementation:** Added RegexMapping to map `minecraft:block/pink_petals`.
- **pointed_dripstone**
- **Error Description:** `Blockstate::Variants` -> renderer.get_top -> Variants::Single -> …

Extend palette blocks support.

---

fastnbt/src/lib.rs
fastnbt/src/ser/serializer.rs
fastnbt/src/test/ser.rs

This PR:
- Adds an extra param `serialize_root_name` to `SerOpts` along with helper methods.
- Gives extra functionality to a Serializer with `serialize_root_name` set to **false**.
- Adds a unit test to ensure it works.
Closes #114

feat(fastnbt): add network nbt to serializer

---

Cargo.lock
fastanvil/Cargo.toml
fastanvil/src/region.rs

Close #101
At first I tried using `lz4_flex` directly, but that doesn't work because java uses a different format. Then I searched "lz4 java" in crates.io and I found this nice crate that implements exactly what we need.
We need a `Lz4DecoderWrapper` because the API of that crate is not the same as the gzip crates. This introduces an additional copy but I believe the only way to avoid that would be to change the interface of the `read_compressed_chunk` function.
Tested by generating a world using a server with `region-file-compression=lz4`, and using the `region-dump` binary to test decompressing it.

Implement LZ4 decompression for 1.20.5+

---

fastnbt/src/lib.rs

This little quality of life PR:
> - Adds the method `fastnbt::from_reader_with_opts` since for some reason creating a Deserializer by hand wasn't working due to some private types.

feat(fastnbt): add `from_reader_with_opts`

---

fastnbt/src/input.rs

Other crates could not access those types directly, but compared with previous code, this won't cause compiler error when calling `Deserializer::from_bytes` and `Deserializer::from_reader`.
- Fix #117
- Fix #118

Make `input::Reader` and `input::Slice` public internally
